#!/bin/bash

OP=$1
id=$2

PARAMS=""

ARGUMENT_LIST=(
  "port"
  "lock"
)

opts=$(getopt --longoptions "$(printf "%s:," "${ARGUMENT_LIST[@]}")" --name $(basename "$0") --options "" -- "$@")

eval set --$opts

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --port)
      PORT=$2
      shift 2
      ;;
    --lock)
      LOCK=$2
      shift 2
      ;;
    *)
      break
      ;;
  esac
done

eval set -- "$PARAMS"

if [[ -z $PORT ]]; then
  PORT="8000"
fi

if [[ -z $LOCK ]]; then
  LOCK="false"
fi

if [[ "$OP" == "select" ]]; then
  id=$(curl -d "id=$id&lock=$LOCK" -X POST "http://localhost:$PORT/camera_vertex" 2>/dev/null);
fi
