#!/bin/bash

OP=$1
SOURCE=$2
TARGET=$3

PARAMS=""

ARGUMENT_LIST=(
  "sheet-id"
  "port"
  "host"
)

opts=$(getopt --longoptions "$(printf "%s:," "${ARGUMENT_LIST[@]}")" --name $(basename "$0") --options "" -- "$@")

eval set --$opts

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --port)
      PORT=$2
      shift 2
      ;;
    --host)
      HOST=$2
      shift 2
      ;;
    --sheet-id)
      SHEET_ID=$2;
      shift 2;
      ;;
    *)
      break
      ;;
  esac
done

eval set -- "$PARAMS"

if [[ -z $PORT ]]; then
  PORT="8000"
fi

if [[ -z $HOST ]]; then
  HOST="http://localhost"
fi

curl -d "sheetId=$SHEET_ID" -X POST "$HOST:$PORT/graph/clear"
